### ISSUE TITLE
cambio del formato y el diseño de la pagina de acceso de clientes

### ISSUE THREAD

**Issue by mpm0126** [mpm0126/GesPro_003#1]
Se requiere cambiar el aspecto visual.
Mejorar acceso para personas con problemas sensoriales.

**Comment by mvs0043** [comment]
Se considera que el mantenimiento evolutivo debe ser realizado y que el objetivo para la realización del mismo debe ser completarlo en un plazo inferior a 5 días laborables. Se crea issue asociado a dicho trabajo.
